### ISSUE TITLE
Top-level game portal containing game portals for each game type

### ISSUE THREAD

**Issue by haykam821** [NucleoidMC/Game-Configs#26]
In conjunction with NucleoidMC/nucleoid-extras#90, a top-level game portal would allow players to join games without having to move around in the world or use commands.

**Comment by ShockMicro** [comment]
If I can get a quick clarification on how the portal linking inside portals works, I'll do it right now.

**Comment by ShockMicro** [comment]
I looked on the Plasmid repo to see if I could get a hint and I can guess how it's supposed to work but I couldn't figure it out for sure.

**Comment by haykam821** [comment]
NucleoidMC/plasmid#221 implements portal GUI menu entries, which will make nesting possible in menu game portals.

**Comment by ShockMicro** [comment]
With the Menufication and Navigation Update, it should be safe to enable the Navigator on the server, and therefore this issue should be able to be closed.
