### ISSUE TITLE
The Towers icon is air

### ISSUE THREAD

**Issue by haykam821** [NucleoidMC/Game-Configs#43]
Because `minecraft:stone_wall` is not an item, the icon defaults to air:

https://github.com/NucleoidMC/Game-Configs/blob/30c6924fb1a15606ebf944e0b318dc7e075de591/data/nucleoid/game_portals/the_towers.json#L3

**Comment by ShockMicro** [comment]
is stone wall seriously not an item? i could've sworn...

**Comment by haykam821** [comment]
These are the walls to choose from:

<img width="573" alt="Collection of walls in the creative inventory" src="https://user-images.githubusercontent.com/24855774/213571188-dae0a82b-0bf3-4740-a009-718e69ac0dd8.png">

I would note that The Towers isn't particularly themed around stone, so a better fitting choice could be `minecraft:nether_brick_fence`.
