### ISSUE TITLE
King of the Hill icon has glint

### ISSUE THREAD

**Issue by haykam821** [NucleoidMC/Game-Configs#44]
King of the Hill uses `minecraft:debug_stick` as its icon, which has glint by default:

https://github.com/NucleoidMC/Game-Configs/blob/30c6924fb1a15606ebf944e0b318dc7e075de591/data/nucleoid/game_portals/koth.json#L3 https://github.com/NucleoidMC/Game-Configs/blob/30c6924fb1a15606ebf944e0b318dc7e075de591/data/nucleoid/games/koth/classic.json#L18

**Comment by ShockMicro** [comment]
intentional

**Comment by haykam821** [comment]
The issue with glint is that it unnecessarily brings attention to the King of the Hill icon, rather than icons that are highlighted for a reason. The navigator currently adds glint to the currently selected mode between viewing all games and open games, and in the future, it may add glint to games with players currently in them, for example.

**Comment by ShockMicro** [comment]
ah, okay, just uh. remind me when i'm in a less Do Nothing mood then

**Comment by haykam821** [comment]
While the top-level icon has been fixed, the icon for 'KotH: Classic' still has glint:

https://github.com/NucleoidMC/Game-Configs/blob/bcc4a1e1c36f57678b7b28bf35452aa42c23120b/data/nucleoid/games/koth/classic.json#L15
